name: CI-CD Docker SSM Teams

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    outputs:
      deployment_status: success

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::585853585762:role/GithubActionOIDC
          aws-region: us-east-1

      - name: Build Docker Image
        run: |
          docker build -t cicd-app .

      - name: Deploy via SSM
        run: |
          aws ssm send-command \
            --instance-ids "i-0f438ea66d8368e21" \
            --document-name "AWS-RunShellScript" \
            --parameters commands='["cd /home/ubuntu && ./deploy.sh"]'

  notify-success:
    needs: deploy
    if: success()

    uses: ./.github/workflows/reusable-teams-notification.yml

    with:
      payload: |
        {
          "text": "✅ Deployment Successful

          Repository: ${{ github.repository }}
          Branch: ${{ github.ref_name }}
          Triggered By: ${{ github.actor }}

          Workflow:
          ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        }

    secrets:
      TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}

  notify-failure:
    needs: deploy
    if: failure()

    uses: ./.github/workflows/reusable-teams-notification.yml

    with:
      payload: |
        {
          "text": "❌ Deployment Failed

          Repository: ${{ github.repository }}
          Branch: ${{ github.ref_name }}
          Triggered By: ${{ github.actor }}

          Workflow:
          ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        }

    secrets:
      TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
